Token { token_kind: INT, spelling: "int", token_position: SourcePosition { line_start: 1, line_finish: 1, char_start: 1, char_end: 3 } }
Token { token_kind: ID, spelling: "i", token_position: SourcePosition { line_start: 1, line_finish: 1, char_start: 5, char_end: 5 } }
Token { token_kind: SEMICOLON, spelling: ";", token_position: SourcePosition { line_start: 1, line_finish: 1, char_start: 6, char_end: 6 } }
Token { token_kind: INT, spelling: "int", token_position: SourcePosition { line_start: 2, line_finish: 2, char_start: 1, char_end: 3 } }
Token { token_kind: ID, spelling: "j", token_position: SourcePosition { line_start: 2, line_finish: 2, char_start: 5, char_end: 5 } }
Token { token_kind: SEMICOLON, spelling: ";", token_position: SourcePosition { line_start: 2, line_finish: 2, char_start: 6, char_end: 6 } }
Token { token_kind: INT, spelling: "int", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 1, char_end: 3 } }
Token { token_kind: ID, spelling: "gcd", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 5, char_end: 7 } }
Token { token_kind: LPAREN, spelling: "(", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 8, char_end: 8 } }
Token { token_kind: INT, spelling: "int", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 9, char_end: 11 } }
Token { token_kind: ID, spelling: "a", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 13, char_end: 13 } }
Token { token_kind: COMMA, spelling: ",", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 14, char_end: 14 } }
Token { token_kind: INT, spelling: "int", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 16, char_end: 18 } }
Token { token_kind: ID, spelling: "b", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 20, char_end: 20 } }
Token { token_kind: RPAREN, spelling: ")", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 21, char_end: 21 } }
Token { token_kind: LBRACE, spelling: "{", token_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 23, char_end: 23 } }
Token { token_kind: IF, spelling: "if", token_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 3, char_end: 4 } }
Token { token_kind: LPAREN, spelling: "(", token_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 6, char_end: 6 } }
Token { token_kind: ID, spelling: "b", token_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 7, char_end: 7 } }
Token { token_kind: EQEQ, spelling: "==", token_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 9, char_end: 10 } }
Token { token_kind: INTLITERAL, spelling: "0", token_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 12, char_end: 12 } }
Token { token_kind: RPAREN, spelling: ")", token_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 13, char_end: 13 } }
Token { token_kind: RETURN, spelling: "return", token_position: SourcePosition { line_start: 6, line_finish: 6, char_start: 5, char_end: 10 } }
Token { token_kind: ID, spelling: "a", token_position: SourcePosition { line_start: 6, line_finish: 6, char_start: 12, char_end: 12 } }
Token { token_kind: SEMICOLON, spelling: ";", token_position: SourcePosition { line_start: 6, line_finish: 6, char_start: 13, char_end: 13 } }
Token { token_kind: ELSE, spelling: "else", token_position: SourcePosition { line_start: 7, line_finish: 7, char_start: 3, char_end: 6 } }
Token { token_kind: RETURN, spelling: "return", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 3, char_end: 8 } }
Token { token_kind: ID, spelling: "gcd", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 10, char_end: 12 } }
Token { token_kind: LPAREN, spelling: "(", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 13, char_end: 13 } }
Token { token_kind: ID, spelling: "b", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 14, char_end: 14 } }
Token { token_kind: COMMA, spelling: ",", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 15, char_end: 15 } }
Token { token_kind: ID, spelling: "a", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 17, char_end: 17 } }
Token { token_kind: MINUS, spelling: "-", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 19, char_end: 19 } }
Token { token_kind: LPAREN, spelling: "(", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 21, char_end: 21 } }
Token { token_kind: ID, spelling: "a", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 22, char_end: 22 } }
Token { token_kind: DIV, spelling: "/", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 23, char_end: 23 } }
Token { token_kind: ID, spelling: "b", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 24, char_end: 24 } }
Token { token_kind: RPAREN, spelling: ")", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 25, char_end: 25 } }
Token { token_kind: MULT, spelling: "*", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 27, char_end: 27 } }
Token { token_kind: ID, spelling: "b", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 28, char_end: 28 } }
Token { token_kind: RPAREN, spelling: ")", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 29, char_end: 29 } }
Token { token_kind: SEMICOLON, spelling: ";", token_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 30, char_end: 30 } }
Token { token_kind: RBRACE, spelling: "}", token_position: SourcePosition { line_start: 9, line_finish: 9, char_start: 1, char_end: 1 } }
Token { token_kind: VOID, spelling: "void", token_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 1, char_end: 4 } }
Token { token_kind: ID, spelling: "main", token_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 6, char_end: 9 } }
Token { token_kind: LPAREN, spelling: "(", token_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 10, char_end: 10 } }
Token { token_kind: RPAREN, spelling: ")", token_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 11, char_end: 11 } }
Token { token_kind: LBRACE, spelling: "{", token_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 13, char_end: 13 } }
Token { token_kind: ID, spelling: "i", token_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 3, char_end: 3 } }
Token { token_kind: EQ, spelling: "=", token_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 5, char_end: 5 } }
Token { token_kind: ID, spelling: "getInt", token_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 7, char_end: 12 } }
Token { token_kind: LPAREN, spelling: "(", token_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 13, char_end: 13 } }
Token { token_kind: RPAREN, spelling: ")", token_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 14, char_end: 14 } }
Token { token_kind: SEMICOLON, spelling: ";", token_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 15, char_end: 15 } }
Token { token_kind: ID, spelling: "j", token_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 3, char_end: 3 } }
Token { token_kind: EQ, spelling: "=", token_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 5, char_end: 5 } }
Token { token_kind: ID, spelling: "getInt", token_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 7, char_end: 12 } }
Token { token_kind: LPAREN, spelling: "(", token_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 13, char_end: 13 } }
Token { token_kind: RPAREN, spelling: ")", token_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 14, char_end: 14 } }
Token { token_kind: SEMICOLON, spelling: ";", token_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 15, char_end: 15 } }
Token { token_kind: ID, spelling: "putIntLn", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 3, char_end: 10 } }
Token { token_kind: LPAREN, spelling: "(", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 11, char_end: 11 } }
Token { token_kind: ID, spelling: "gcd", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 12, char_end: 14 } }
Token { token_kind: LPAREN, spelling: "(", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 15, char_end: 15 } }
Token { token_kind: ID, spelling: "i", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 16, char_end: 16 } }
Token { token_kind: COMMA, spelling: ",", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 17, char_end: 17 } }
Token { token_kind: ID, spelling: "j", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 19, char_end: 19 } }
Token { token_kind: RPAREN, spelling: ")", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 20, char_end: 20 } }
Token { token_kind: RPAREN, spelling: ")", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 21, char_end: 21 } }
Token { token_kind: SEMICOLON, spelling: ";", token_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 22, char_end: 22 } }
Token { token_kind: RBRACE, spelling: "}", token_position: SourcePosition { line_start: 14, line_finish: 14, char_start: 1, char_end: 1 } }
Token { token_kind: EOF, spelling: "$", token_position: SourcePosition { line_start: 15, line_finish: 15, char_start: 1, char_end: 1 } }
