ScannerToken { token_kind: INT, token_spelling: "int", source_position: SourcePosition { line_start: 1, line_finish: 1, char_start: 1, char_end: 3 } }
ScannerToken { token_kind: ID, token_spelling: "i", source_position: SourcePosition { line_start: 1, line_finish: 1, char_start: 5, char_end: 5 } }
ScannerToken { token_kind: SEMICOLON, token_spelling: ";", source_position: SourcePosition { line_start: 1, line_finish: 1, char_start: 6, char_end: 6 } }
ScannerToken { token_kind: INT, token_spelling: "int", source_position: SourcePosition { line_start: 2, line_finish: 2, char_start: 1, char_end: 3 } }
ScannerToken { token_kind: ID, token_spelling: "j", source_position: SourcePosition { line_start: 2, line_finish: 2, char_start: 5, char_end: 5 } }
ScannerToken { token_kind: SEMICOLON, token_spelling: ";", source_position: SourcePosition { line_start: 2, line_finish: 2, char_start: 6, char_end: 6 } }
ScannerToken { token_kind: INT, token_spelling: "int", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 1, char_end: 3 } }
ScannerToken { token_kind: ID, token_spelling: "gcd", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 5, char_end: 7 } }
ScannerToken { token_kind: LPAREN, token_spelling: "(", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 8, char_end: 8 } }
ScannerToken { token_kind: INT, token_spelling: "int", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 9, char_end: 11 } }
ScannerToken { token_kind: ID, token_spelling: "a", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 13, char_end: 13 } }
ScannerToken { token_kind: COMMA, token_spelling: ",", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 14, char_end: 14 } }
ScannerToken { token_kind: INT, token_spelling: "int", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 16, char_end: 18 } }
ScannerToken { token_kind: ID, token_spelling: "b", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 20, char_end: 20 } }
ScannerToken { token_kind: RPAREN, token_spelling: ")", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 21, char_end: 21 } }
ScannerToken { token_kind: LBRACE, token_spelling: "{", source_position: SourcePosition { line_start: 4, line_finish: 4, char_start: 23, char_end: 23 } }
ScannerToken { token_kind: IF, token_spelling: "if", source_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 3, char_end: 4 } }
ScannerToken { token_kind: LPAREN, token_spelling: "(", source_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 6, char_end: 6 } }
ScannerToken { token_kind: ID, token_spelling: "b", source_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 7, char_end: 7 } }
ScannerToken { token_kind: EQEQ, token_spelling: "==", source_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 9, char_end: 10 } }
ScannerToken { token_kind: ID, token_spelling: "0", source_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 12, char_end: 12 } }
ScannerToken { token_kind: RPAREN, token_spelling: ")", source_position: SourcePosition { line_start: 5, line_finish: 5, char_start: 13, char_end: 13 } }
ScannerToken { token_kind: RETURN, token_spelling: "return", source_position: SourcePosition { line_start: 6, line_finish: 6, char_start: 5, char_end: 10 } }
ScannerToken { token_kind: ID, token_spelling: "a", source_position: SourcePosition { line_start: 6, line_finish: 6, char_start: 12, char_end: 12 } }
ScannerToken { token_kind: SEMICOLON, token_spelling: ";", source_position: SourcePosition { line_start: 6, line_finish: 6, char_start: 13, char_end: 13 } }
ScannerToken { token_kind: ELSE, token_spelling: "else", source_position: SourcePosition { line_start: 7, line_finish: 7, char_start: 3, char_end: 6 } }
ScannerToken { token_kind: RETURN, token_spelling: "return", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 3, char_end: 8 } }
ScannerToken { token_kind: ID, token_spelling: "gcd", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 10, char_end: 12 } }
ScannerToken { token_kind: LPAREN, token_spelling: "(", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 13, char_end: 13 } }
ScannerToken { token_kind: ID, token_spelling: "b", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 14, char_end: 14 } }
ScannerToken { token_kind: COMMA, token_spelling: ",", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 15, char_end: 15 } }
ScannerToken { token_kind: ID, token_spelling: "a", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 17, char_end: 17 } }
ScannerToken { token_kind: MINUS, token_spelling: "-", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 19, char_end: 19 } }
ScannerToken { token_kind: LPAREN, token_spelling: "(", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 21, char_end: 21 } }
ScannerToken { token_kind: ID, token_spelling: "a", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 22, char_end: 22 } }
ScannerToken { token_kind: DIV, token_spelling: "/", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 23, char_end: 23 } }
ScannerToken { token_kind: ID, token_spelling: "b", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 24, char_end: 24 } }
ScannerToken { token_kind: RPAREN, token_spelling: ")", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 25, char_end: 25 } }
ScannerToken { token_kind: MULT, token_spelling: "*", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 27, char_end: 27 } }
ScannerToken { token_kind: ID, token_spelling: "b", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 28, char_end: 28 } }
ScannerToken { token_kind: RPAREN, token_spelling: ")", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 29, char_end: 29 } }
ScannerToken { token_kind: SEMICOLON, token_spelling: ";", source_position: SourcePosition { line_start: 8, line_finish: 8, char_start: 30, char_end: 30 } }
ScannerToken { token_kind: RBRACE, token_spelling: "}", source_position: SourcePosition { line_start: 9, line_finish: 9, char_start: 1, char_end: 1 } }
ScannerToken { token_kind: VOID, token_spelling: "void", source_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 1, char_end: 4 } }
ScannerToken { token_kind: ID, token_spelling: "main", source_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 6, char_end: 9 } }
ScannerToken { token_kind: LPAREN, token_spelling: "(", source_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 10, char_end: 10 } }
ScannerToken { token_kind: RPAREN, token_spelling: ")", source_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 11, char_end: 11 } }
ScannerToken { token_kind: LBRACE, token_spelling: "{", source_position: SourcePosition { line_start: 10, line_finish: 10, char_start: 13, char_end: 13 } }
ScannerToken { token_kind: ID, token_spelling: "i", source_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 3, char_end: 3 } }
ScannerToken { token_kind: EQ, token_spelling: "=", source_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 5, char_end: 5 } }
ScannerToken { token_kind: ID, token_spelling: "getInt", source_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 7, char_end: 12 } }
ScannerToken { token_kind: LPAREN, token_spelling: "(", source_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 13, char_end: 13 } }
ScannerToken { token_kind: RPAREN, token_spelling: ")", source_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 14, char_end: 14 } }
ScannerToken { token_kind: SEMICOLON, token_spelling: ";", source_position: SourcePosition { line_start: 11, line_finish: 11, char_start: 15, char_end: 15 } }
ScannerToken { token_kind: ID, token_spelling: "j", source_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 3, char_end: 3 } }
ScannerToken { token_kind: EQ, token_spelling: "=", source_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 5, char_end: 5 } }
ScannerToken { token_kind: ID, token_spelling: "getInt", source_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 7, char_end: 12 } }
ScannerToken { token_kind: LPAREN, token_spelling: "(", source_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 13, char_end: 13 } }
ScannerToken { token_kind: RPAREN, token_spelling: ")", source_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 14, char_end: 14 } }
ScannerToken { token_kind: SEMICOLON, token_spelling: ";", source_position: SourcePosition { line_start: 12, line_finish: 12, char_start: 15, char_end: 15 } }
ScannerToken { token_kind: ID, token_spelling: "putIntLn", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 3, char_end: 10 } }
ScannerToken { token_kind: LPAREN, token_spelling: "(", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 11, char_end: 11 } }
ScannerToken { token_kind: ID, token_spelling: "gcd", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 12, char_end: 14 } }
ScannerToken { token_kind: LPAREN, token_spelling: "(", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 15, char_end: 15 } }
ScannerToken { token_kind: ID, token_spelling: "i", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 16, char_end: 16 } }
ScannerToken { token_kind: COMMA, token_spelling: ",", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 17, char_end: 17 } }
ScannerToken { token_kind: ID, token_spelling: "j", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 19, char_end: 19 } }
ScannerToken { token_kind: RPAREN, token_spelling: ")", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 20, char_end: 20 } }
ScannerToken { token_kind: RPAREN, token_spelling: ")", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 21, char_end: 21 } }
ScannerToken { token_kind: SEMICOLON, token_spelling: ";", source_position: SourcePosition { line_start: 13, line_finish: 13, char_start: 22, char_end: 22 } }
ScannerToken { token_kind: RBRACE, token_spelling: "}", source_position: SourcePosition { line_start: 14, line_finish: 14, char_start: 1, char_end: 1 } }
ScannerToken { token_kind: EOF, token_spelling: "$", source_position: SourcePosition { line_start: 15, line_finish: 15, char_start: 1, char_end: 1 } }
